<?php
/**
 * See LICENSE.md for license details.
 */
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('Proin ut enim urna. Nullam quis purus id tortor consequat maximus. Aliquam placerat mauris tincidunt sapien condimentum semper.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('Proin ut enim urna. Nullam quis purus id tortor consequat maximus. Aliquam placerat mauris tincidunt sapien condimentum semper. Proin feugiat ultricies felis, quis consequat mi consequat vitae. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit.')) ?>
    </p>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('Addressfactory & Magento')) ?></h3>
            <p>
                <?= $block->escapeHtml(__('Proin ut enim urna. Nullam quis purus id tortor consequat maximus. Aliquam placerat mauris tincidunt sapien condimentum semper.')) ?>
            </p>
        </div>
    </aside>
</div>
