<?php
/**
 * See LICENSE.md for license details.
 */
use Magento\Backend\Block\Template;
use PostDirekt\Addressfactory\ViewModel\Adminhtml\AnalysisData;

/** @var Template $block */
if (!$block->getData('template_should_display')) {
    // This value is set by PostDirekt\Addressfactory\Observer\MoveAnalysisBox
    return;
}

/** @var AnalysisData $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="admin__page-section-item order-shipping-address pd_infox_box">
    <div class="admin__page-section-item-title">
        <img class="pd_logo" src='<?= $viewModel->getLogoUrl() ?>' alt="logo" width="150px">
        <h2 class="title"><?= $escaper->escapeHtml(__('Shipping Address Check')) ?></h2>
    </div>

    <?php if ($viewModel->showAnalysisResults()): ?>
        <span class="deliverability_score <?= $escaper->escapeHtmlAttr($viewModel->getScore()) ?>">
            <?= $escaper->escapeHtml($viewModel->getHumanReadableScore()) ?>
        </span>
        <div class="detected_issues_info">
            <?php if ($infos = $viewModel->getDetectedIssues()): ?>
                <h4><?= $escaper->escapeHtml(__('Address Information'))?></h4>
                <ul>
                <?php foreach ($infos as $info): ?>
                    <li>
                        <?php if ($info['icon'] !== ''): ?>
                        <span class="icon <?= $escaper->escapeHtmlAttr($info['icon']) ?>"
                              title="<?= $escaper->escapeHtmlAttr($info['code']) ?>">
                        <?php else: ?>
                        <span title="<?= $escaper->escapeHtmlAttr($info['code']) ?>">
                        <?php endif; ?>
                            <?= $escaper->escapeHtml($info['label']) ?>
                        </span>
                    </li>
                <?php endforeach;?>
                </ul>
            <?php endif; ?>
        </div>

        <?php if ($viewModel->showSuggestedAddress()): ?>
            <div class="pd_address_sugestion">
                <h3><?= $escaper->escapeHtml(__('Suggested Shipping Address')) ?></h3>
                <dl>
                    <?= /** @noEscape */ $viewModel->getFormattedAddress() ?>
                </dl>

                <?php if ($viewModel->allowAddressCorrect()): ?>
                    <a class="button action-primary icon icon-import"
                        href="<?= $escaper->escapeUrl($viewModel->getPerformAddressAutocorrectUrl())?>"
                    ><?= $escaper->escapeHtml(__('Auto-Correct Address'))?></a>
                <?php endif; ?>

            </div>
        <?php endif; ?>

        <div class="pd_infox_box action-buttons">
            <h3><?= $escaper->escapeHtml(__('Other Actions')) ?></h3>
            <p>
                <a class="button action-default icon icon-edit"
                   href="<?= $escaper->escapeUrl($viewModel->getManualEditUrl()) ?>"
                ><?= $escaper->escapeHtml(__('Manually Edit Address')) ?></a>
            </p>
            <?php if ($viewModel->showUnholdButton()): ?>
                <p>
                    <button id="order-view-addressfactory-unhold-button"
                       class="button action-default icon icon-success"
                       data-url="<?= $viewModel->getUnholdOrderUrl() ?>"
                    ><?= $escaper->escapeHtml(__('Unhold Order'))?></button>
                </p>
            <?php endif; ?>

            <?php if ($viewModel->showCancelButton()): ?>
                <p>
                    <button id="order-view-addressfactory-cancel-button"
                            class="button action-secondary icon icon-cancel"
                            data-url="<?= $viewModel->getCancelOrderUrl()?>"
                    ><?= $escaper->escapeHtml(__('Cancel Order'))?></button>
                </p>
            <?php endif; ?>
        </div>
        <script type="text/x-magento-init">
            {
                "*": {
                    "PostDirekt_Addressfactory/js/postdirekt-post-wrapper": {}
                }
            }
        </script>

    <?php else: ?>
        <a
            class="button action-primary"
            href="<?= $escaper->escapeUrl($viewModel->getPerformAnalysisUrl()) ?>">
            <?= $escaper->escapeHtml(__('Perform Shipping Address Check')) ?>
        </a>
    <?php endif; ?>
</div>
